import Link from 'next/link';
import { headers } from 'next/headers';
import { SpinningMark } from '@/components/SpinningMark';
import { pickLang } from '@/lib/copy';

export const dynamic = 'force-dynamic';

const COPY = {
  de: {
    tagline: 'Dein KI-Audio-Stadtguide. Laufen, radeln, zuhören – tuur erzählt dir, was du gerade siehst.',
    partner: 'Partnerportal',
    imprint: 'Impressum',
    privacy: 'Datenschutz',
    terms: 'AGB',
    ai: 'Die Erzählungen werden von KI aus öffentlichen Quellen erzeugt.',
  },
  en: {
    tagline: 'Your AI audio city guide. Walk, cycle, listen – tuur tells you about what you are looking at.',
    partner: 'Partner portal',
    imprint: 'Imprint',
    privacy: 'Privacy',
    terms: 'Terms',
    ai: 'Narrations are generated by AI from public sources.',
  },
} as const;

export default async function Home() {
  const lang = pickLang((await headers()).get('accept-language'));
  const c = COPY[lang];
  return (
    <main className="hero" lang={lang}>
      <SpinningMark size={88} label="tuur" />
      <img src="/brand/tuur-wordmark-red.svg" alt="tuur" width={220} />
      <p>{c.tagline}</p>
      <p className="small">{c.ai}</p>
      <div className="stores">
        <Link className="pill" href="/partner">
          {c.partner}
        </Link>
      </div>
      <nav className="foot" aria-label="Legal">
        <Link href={`/legal/imprint?lang=${lang}`}>{c.imprint}</Link>
        <Link href={`/legal/privacy?lang=${lang}`}>{c.privacy}</Link>
        <Link href={`/legal/terms?lang=${lang}`}>{c.terms}</Link>
      </nav>
    </main>
  );
}
