import type { CityBadgeIcon } from './types';

export interface CityBadgeDef {
  /** Stable slug, lowercase ascii with dashes, e.g. 'berlin', 'new-york', 'rio-de-janeiro'. Never change once shipped. */
  id: string;
  names: { de: string; en: string };
  /** ISO 3166-1 alpha-2, uppercase. */
  country: string;
  /** City centre (historic centre / main square), WGS84, 4 decimals. */
  center: { lat: number; lng: number };
  /** Radius in km around the centre in which a completed tour counts for this city (typically 5-25, larger for sprawling metros). */
  radiusKm: number;
  /** The one landmark that symbolises the city, short, in both languages. */
  landmark: { de: string; en: string };
  icon: CityBadgeIcon;
}

/** Collectible city badges for major tourist destinations (curated; names in de/en). Generated, review before release. */
export const CITY_BADGES: readonly CityBadgeDef[] = [
  {
    id: 'abu-dhabi',
    names: { de: 'Abu Dhabi', en: 'Abu Dhabi' },
    country: 'AE',
    center: { lat: 24.4539, lng: 54.3773 },
    radiusKm: 25,
    landmark: { de: 'Scheich-Zayid-Moschee', en: 'Sheikh Zayed Grand Mosque' },
    icon: 'mosque',
  },
  {
    id: 'agra',
    names: { de: 'Agra', en: 'Agra' },
    country: 'IN',
    center: { lat: 27.1767, lng: 78.0081 },
    radiusKm: 12,
    landmark: { de: 'Taj Mahal', en: 'Taj Mahal' },
    icon: 'mosque',
  },
  {
    id: 'amsterdam',
    names: { de: 'Amsterdam', en: 'Amsterdam' },
    country: 'NL',
    center: { lat: 52.3731, lng: 4.8926 },
    radiusKm: 10,
    landmark: { de: 'Grachtengürtel', en: 'Canal Ring' },
    icon: 'bridge',
  },
  {
    id: 'antalya',
    names: { de: 'Antalya', en: 'Antalya' },
    country: 'TR',
    center: { lat: 36.8841, lng: 30.7056 },
    radiusKm: 20,
    landmark: { de: 'Altstadt Kaleiçi', en: 'Kaleiçi Old Town' },
    icon: 'beach',
  },
  {
    id: 'antwerp',
    names: { de: 'Antwerpen', en: 'Antwerp' },
    country: 'BE',
    center: { lat: 51.2213, lng: 4.3997 },
    radiusKm: 8,
    landmark: { de: 'Liebfrauenkathedrale', en: 'Cathedral of Our Lady' },
    icon: 'church',
  },
  {
    id: 'athens',
    names: { de: 'Athen', en: 'Athens' },
    country: 'GR',
    center: { lat: 37.9755, lng: 23.7348 },
    radiusKm: 15,
    landmark: { de: 'Akropolis', en: 'Acropolis' },
    icon: 'pillar',
  },
  {
    id: 'auckland',
    names: { de: 'Auckland', en: 'Auckland' },
    country: 'NZ',
    center: { lat: -36.8485, lng: 174.7633 },
    radiusKm: 20,
    landmark: { de: 'Viaduct Harbour', en: 'Viaduct Harbour' },
    icon: 'sail-boat',
  },
  {
    id: 'bangkok',
    names: { de: 'Bangkok', en: 'Bangkok' },
    country: 'TH',
    center: { lat: 13.7563, lng: 100.5018 },
    radiusKm: 25,
    landmark: { de: 'Wat Arun', en: 'Wat Arun' },
    icon: 'temple-buddhist',
  },
  {
    id: 'barcelona',
    names: { de: 'Barcelona', en: 'Barcelona' },
    country: 'ES',
    center: { lat: 41.3874, lng: 2.1686 },
    radiusKm: 12,
    landmark: { de: 'Sagrada Família', en: 'Sagrada Família' },
    icon: 'church',
  },
  {
    id: 'beijing',
    names: { de: 'Peking', en: 'Beijing' },
    country: 'CN',
    center: { lat: 39.9042, lng: 116.4074 },
    radiusKm: 30,
    landmark: { de: 'Verbotene Stadt', en: 'Forbidden City' },
    icon: 'castle',
  },
  {
    id: 'bergen',
    names: { de: 'Bergen', en: 'Bergen' },
    country: 'NO',
    center: { lat: 60.3929, lng: 5.3241 },
    radiusKm: 8,
    landmark: { de: 'Bryggen', en: 'Bryggen' },
    icon: 'home-city',
  },
  {
    id: 'berlin',
    names: { de: 'Berlin', en: 'Berlin' },
    country: 'DE',
    center: { lat: 52.52, lng: 13.405 },
    radiusKm: 20,
    landmark: { de: 'Brandenburger Tor', en: 'Brandenburg Gate' },
    icon: 'pillar',
  },
  {
    id: 'bern',
    names: { de: 'Bern', en: 'Bern' },
    country: 'CH',
    center: { lat: 46.948, lng: 7.4474 },
    radiusKm: 6,
    landmark: { de: 'Zytglogge', en: 'Zytglogge Clock Tower' },
    icon: 'home-city',
  },
  {
    id: 'bordeaux',
    names: { de: 'Bordeaux', en: 'Bordeaux' },
    country: 'FR',
    center: { lat: 44.8378, lng: -0.5792 },
    radiusKm: 10,
    landmark: { de: 'Place de la Bourse', en: 'Place de la Bourse' },
    icon: 'glass-wine',
  },
  {
    id: 'boston',
    names: { de: 'Boston', en: 'Boston' },
    country: 'US',
    center: { lat: 42.3601, lng: -71.0589 },
    radiusKm: 12,
    landmark: { de: 'Freedom Trail', en: 'Freedom Trail' },
    icon: 'home-city',
  },
  {
    id: 'bremen',
    names: { de: 'Bremen', en: 'Bremen' },
    country: 'DE',
    center: { lat: 53.0758, lng: 8.8072 },
    radiusKm: 10,
    landmark: { de: 'Bremer Stadtmusikanten', en: 'Town Musicians of Bremen' },
    icon: 'music',
  },
  {
    id: 'bruges',
    names: { de: 'Brügge', en: 'Bruges' },
    country: 'BE',
    center: { lat: 51.2089, lng: 3.2242 },
    radiusKm: 6,
    landmark: { de: 'Belfried', en: 'Belfry of Bruges' },
    icon: 'bridge',
  },
  {
    id: 'brussels',
    names: { de: 'Brüssel', en: 'Brussels' },
    country: 'BE',
    center: { lat: 50.8467, lng: 4.3525 },
    radiusKm: 10,
    landmark: { de: 'Grand-Place', en: 'Grand-Place' },
    icon: 'home-city',
  },
  {
    id: 'budapest',
    names: { de: 'Budapest', en: 'Budapest' },
    country: 'HU',
    center: { lat: 47.4979, lng: 19.0402 },
    radiusKm: 15,
    landmark: { de: 'Kettenbrücke', en: 'Széchenyi Chain Bridge' },
    icon: 'bridge',
  },
  {
    id: 'buenos-aires',
    names: { de: 'Buenos Aires', en: 'Buenos Aires' },
    country: 'AR',
    center: { lat: -34.6037, lng: -58.3816 },
    radiusKm: 25,
    landmark: { de: 'Obelisco', en: 'Obelisco' },
    icon: 'pillar',
  },
  {
    id: 'cairo',
    names: { de: 'Kairo', en: 'Cairo' },
    country: 'EG',
    center: { lat: 30.0444, lng: 31.2357 },
    radiusKm: 25,
    landmark: { de: 'Pyramiden von Gizeh', en: 'Pyramids of Giza' },
    icon: 'pillar',
  },
  {
    id: 'cancun',
    names: { de: 'Cancún', en: 'Cancún' },
    country: 'MX',
    center: { lat: 21.1619, lng: -86.8515 },
    radiusKm: 20,
    landmark: { de: 'Playa Delfines', en: 'Playa Delfines' },
    icon: 'beach',
  },
  {
    id: 'cape-town',
    names: { de: 'Kapstadt', en: 'Cape Town' },
    country: 'ZA',
    center: { lat: -33.9249, lng: 18.4241 },
    radiusKm: 20,
    landmark: { de: 'Tafelberg', en: 'Table Mountain' },
    icon: 'gondola',
  },
  {
    id: 'cartagena',
    names: { de: 'Cartagena', en: 'Cartagena' },
    country: 'CO',
    center: { lat: 10.4236, lng: -75.5496 },
    radiusKm: 10,
    landmark: { de: 'Ummauerte Altstadt', en: 'Walled City' },
    icon: 'castle',
  },
  {
    id: 'chiang-mai',
    names: { de: 'Chiang Mai', en: 'Chiang Mai' },
    country: 'TH',
    center: { lat: 18.7883, lng: 98.9853 },
    radiusKm: 12,
    landmark: { de: 'Wat Phra That Doi Suthep', en: 'Wat Phra That Doi Suthep' },
    icon: 'temple-buddhist',
  },
  {
    id: 'chicago',
    names: { de: 'Chicago', en: 'Chicago' },
    country: 'US',
    center: { lat: 41.8781, lng: -87.6298 },
    radiusKm: 20,
    landmark: { de: 'Cloud Gate', en: 'Cloud Gate' },
    icon: 'city-variant',
  },
  {
    id: 'cologne',
    names: { de: 'Köln', en: 'Cologne' },
    country: 'DE',
    center: { lat: 50.9375, lng: 6.9603 },
    radiusKm: 12,
    landmark: { de: 'Kölner Dom', en: 'Cologne Cathedral' },
    icon: 'church',
  },
  {
    id: 'copenhagen',
    names: { de: 'Kopenhagen', en: 'Copenhagen' },
    country: 'DK',
    center: { lat: 55.6761, lng: 12.5683 },
    radiusKm: 12,
    landmark: { de: 'Nyhavn', en: 'Nyhavn' },
    icon: 'sail-boat',
  },
  {
    id: 'cusco',
    names: { de: 'Cusco', en: 'Cusco' },
    country: 'PE',
    center: { lat: -13.5163, lng: -71.9786 },
    radiusKm: 10,
    landmark: { de: 'Kathedrale von Cusco', en: 'Cusco Cathedral' },
    icon: 'church',
  },
  {
    id: 'doha',
    names: { de: 'Doha', en: 'Doha' },
    country: 'QA',
    center: { lat: 25.2854, lng: 51.531 },
    radiusKm: 20,
    landmark: { de: 'Museum für Islamische Kunst', en: 'Museum of Islamic Art' },
    icon: 'palette',
  },
  {
    id: 'dresden',
    names: { de: 'Dresden', en: 'Dresden' },
    country: 'DE',
    center: { lat: 51.0504, lng: 13.7373 },
    radiusKm: 10,
    landmark: { de: 'Frauenkirche', en: 'Frauenkirche' },
    icon: 'church',
  },
  {
    id: 'dubai',
    names: { de: 'Dubai', en: 'Dubai' },
    country: 'AE',
    center: { lat: 25.2048, lng: 55.2708 },
    radiusKm: 30,
    landmark: { de: 'Burj Khalifa', en: 'Burj Khalifa' },
    icon: 'office-building',
  },
  {
    id: 'dublin',
    names: { de: 'Dublin', en: 'Dublin' },
    country: 'IE',
    center: { lat: 53.3498, lng: -6.2603 },
    radiusKm: 12,
    landmark: { de: 'Guinness Storehouse', en: 'Guinness Storehouse' },
    icon: 'beer',
  },
  {
    id: 'dubrovnik',
    names: { de: 'Dubrovnik', en: 'Dubrovnik' },
    country: 'HR',
    center: { lat: 42.6407, lng: 18.1077 },
    radiusKm: 6,
    landmark: { de: 'Stadtmauern', en: 'City Walls' },
    icon: 'castle',
  },
  {
    id: 'dusseldorf',
    names: { de: 'Düsseldorf', en: 'Düsseldorf' },
    country: 'DE',
    center: { lat: 51.2277, lng: 6.7735 },
    radiusKm: 10,
    landmark: { de: 'Rheinturm', en: 'Rhine Tower' },
    icon: 'office-building',
  },
  {
    id: 'edinburgh',
    names: { de: 'Edinburgh', en: 'Edinburgh' },
    country: 'GB',
    center: { lat: 55.9533, lng: -3.1883 },
    radiusKm: 10,
    landmark: { de: 'Edinburgh Castle', en: 'Edinburgh Castle' },
    icon: 'castle',
  },
  {
    id: 'florence',
    names: { de: 'Florenz', en: 'Florence' },
    country: 'IT',
    center: { lat: 43.7696, lng: 11.2558 },
    radiusKm: 8,
    landmark: { de: 'Dom Santa Maria del Fiore', en: 'Florence Cathedral' },
    icon: 'church',
  },
  {
    id: 'frankfurt',
    names: { de: 'Frankfurt am Main', en: 'Frankfurt' },
    country: 'DE',
    center: { lat: 50.1109, lng: 8.6821 },
    radiusKm: 12,
    landmark: { de: 'Römer', en: 'Römer' },
    icon: 'home-city',
  },
  {
    id: 'geneva',
    names: { de: 'Genf', en: 'Geneva' },
    country: 'CH',
    center: { lat: 46.2044, lng: 6.1432 },
    radiusKm: 10,
    landmark: { de: 'Jet d’Eau', en: 'Jet d’Eau' },
    icon: 'waves',
  },
  {
    id: 'granada',
    names: { de: 'Granada', en: 'Granada' },
    country: 'ES',
    center: { lat: 37.1773, lng: -3.5986 },
    radiusKm: 8,
    landmark: { de: 'Alhambra', en: 'Alhambra' },
    icon: 'castle',
  },
  {
    id: 'hallstatt',
    names: { de: 'Hallstatt', en: 'Hallstatt' },
    country: 'AT',
    center: { lat: 47.5622, lng: 13.6493 },
    radiusKm: 4,
    landmark: { de: 'Hallstätter See', en: 'Lake Hallstatt' },
    icon: 'waves',
  },
  {
    id: 'hamburg',
    names: { de: 'Hamburg', en: 'Hamburg' },
    country: 'DE',
    center: { lat: 53.5511, lng: 9.9937 },
    radiusKm: 15,
    landmark: { de: 'Elbphilharmonie', en: 'Elbphilharmonie' },
    icon: 'music',
  },
  {
    id: 'hanoi',
    names: { de: 'Hanoi', en: 'Hanoi' },
    country: 'VN',
    center: { lat: 21.0285, lng: 105.8542 },
    radiusKm: 15,
    landmark: { de: 'Hoan-Kiem-See', en: 'Hoan Kiem Lake' },
    icon: 'waves',
  },
  {
    id: 'havana',
    names: { de: 'Havanna', en: 'Havana' },
    country: 'CU',
    center: { lat: 23.1368, lng: -82.3533 },
    radiusKm: 12,
    landmark: { de: 'Malecón', en: 'Malecón' },
    icon: 'waves',
  },
  {
    id: 'heidelberg',
    names: { de: 'Heidelberg', en: 'Heidelberg' },
    country: 'DE',
    center: { lat: 49.412, lng: 8.71 },
    radiusKm: 8,
    landmark: { de: 'Heidelberger Schloss', en: 'Heidelberg Castle' },
    icon: 'castle',
  },
  {
    id: 'helsinki',
    names: { de: 'Helsinki', en: 'Helsinki' },
    country: 'FI',
    center: { lat: 60.1699, lng: 24.9384 },
    radiusKm: 12,
    landmark: { de: 'Dom von Helsinki', en: 'Helsinki Cathedral' },
    icon: 'church',
  },
  {
    id: 'ho-chi-minh-city',
    names: { de: 'Ho-Chi-Minh-Stadt', en: 'Ho Chi Minh City' },
    country: 'VN',
    center: { lat: 10.7769, lng: 106.7009 },
    radiusKm: 20,
    landmark: { de: 'Kathedrale Notre-Dame', en: 'Saigon Notre-Dame Cathedral' },
    icon: 'church',
  },
  {
    id: 'hoi-an',
    names: { de: 'Hội An', en: 'Hoi An' },
    country: 'VN',
    center: { lat: 15.8801, lng: 108.338 },
    radiusKm: 6,
    landmark: { de: 'Japanische Brücke', en: 'Japanese Covered Bridge' },
    icon: 'bridge',
  },
  {
    id: 'hong-kong',
    names: { de: 'Hongkong', en: 'Hong Kong' },
    country: 'HK',
    center: { lat: 22.28, lng: 114.1588 },
    radiusKm: 20,
    landmark: { de: 'Victoria Harbour', en: 'Victoria Harbour' },
    icon: 'sail-boat',
  },
  {
    id: 'honolulu',
    names: { de: 'Honolulu', en: 'Honolulu' },
    country: 'US',
    center: { lat: 21.3069, lng: -157.8583 },
    radiusKm: 15,
    landmark: { de: 'Waikīkī Beach', en: 'Waikiki Beach' },
    icon: 'palm-tree',
  },
  {
    id: 'innsbruck',
    names: { de: 'Innsbruck', en: 'Innsbruck' },
    country: 'AT',
    center: { lat: 47.2692, lng: 11.4041 },
    radiusKm: 8,
    landmark: { de: 'Goldenes Dachl', en: 'Golden Roof' },
    icon: 'snowflake',
  },
  {
    id: 'istanbul',
    names: { de: 'Istanbul', en: 'Istanbul' },
    country: 'TR',
    center: { lat: 41.0082, lng: 28.9784 },
    radiusKm: 20,
    landmark: { de: 'Hagia Sophia', en: 'Hagia Sophia' },
    icon: 'mosque',
  },
  {
    id: 'jaipur',
    names: { de: 'Jaipur', en: 'Jaipur' },
    country: 'IN',
    center: { lat: 26.9124, lng: 75.7873 },
    radiusKm: 15,
    landmark: { de: 'Palast der Winde', en: 'Hawa Mahal' },
    icon: 'castle',
  },
  {
    id: 'kathmandu',
    names: { de: 'Kathmandu', en: 'Kathmandu' },
    country: 'NP',
    center: { lat: 27.7172, lng: 85.324 },
    radiusKm: 12,
    landmark: { de: 'Swayambhunath', en: 'Swayambhunath' },
    icon: 'temple-buddhist',
  },
  {
    id: 'krakow',
    names: { de: 'Krakau', en: 'Kraków' },
    country: 'PL',
    center: { lat: 50.0614, lng: 19.9366 },
    radiusKm: 10,
    landmark: { de: 'Wawel', en: 'Wawel Castle' },
    icon: 'castle',
  },
  {
    id: 'kuala-lumpur',
    names: { de: 'Kuala Lumpur', en: 'Kuala Lumpur' },
    country: 'MY',
    center: { lat: 3.139, lng: 101.6869 },
    radiusKm: 20,
    landmark: { de: 'Petronas Towers', en: 'Petronas Towers' },
    icon: 'office-building',
  },
  {
    id: 'kyoto',
    names: { de: 'Kyōto', en: 'Kyoto' },
    country: 'JP',
    center: { lat: 35.0116, lng: 135.7681 },
    radiusKm: 12,
    landmark: { de: 'Goldener Pavillon', en: 'Kinkaku-ji' },
    icon: 'temple-buddhist',
  },
  {
    id: 'las-vegas',
    names: { de: 'Las Vegas', en: 'Las Vegas' },
    country: 'US',
    center: { lat: 36.1699, lng: -115.1398 },
    radiusKm: 20,
    landmark: { de: 'Las Vegas Strip', en: 'Las Vegas Strip' },
    icon: 'city-variant',
  },
  {
    id: 'leipzig',
    names: { de: 'Leipzig', en: 'Leipzig' },
    country: 'DE',
    center: { lat: 51.3397, lng: 12.3731 },
    radiusKm: 10,
    landmark: { de: 'Thomaskirche', en: 'St. Thomas Church' },
    icon: 'music',
  },
  {
    id: 'lisbon',
    names: { de: 'Lissabon', en: 'Lisbon' },
    country: 'PT',
    center: { lat: 38.7139, lng: -9.1394 },
    radiusKm: 12,
    landmark: { de: 'Straßenbahn 28', en: 'Tram 28' },
    icon: 'tram',
  },
  {
    id: 'london',
    names: { de: 'London', en: 'London' },
    country: 'GB',
    center: { lat: 51.5074, lng: -0.1278 },
    radiusKm: 25,
    landmark: { de: 'Tower Bridge', en: 'Tower Bridge' },
    icon: 'bridge',
  },
  {
    id: 'los-angeles',
    names: { de: 'Los Angeles', en: 'Los Angeles' },
    country: 'US',
    center: { lat: 34.0522, lng: -118.2437 },
    radiusKm: 40,
    landmark: { de: 'Hollywood-Schriftzug', en: 'Hollywood Sign' },
    icon: 'camera',
  },
  {
    id: 'lubeck',
    names: { de: 'Lübeck', en: 'Lübeck' },
    country: 'DE',
    center: { lat: 53.8655, lng: 10.6866 },
    radiusKm: 6,
    landmark: { de: 'Holstentor', en: 'Holsten Gate' },
    icon: 'castle',
  },
  {
    id: 'lucerne',
    names: { de: 'Luzern', en: 'Lucerne' },
    country: 'CH',
    center: { lat: 47.0502, lng: 8.3093 },
    radiusKm: 8,
    landmark: { de: 'Kapellbrücke', en: 'Chapel Bridge' },
    icon: 'bridge',
  },
  {
    id: 'luxor',
    names: { de: 'Luxor', en: 'Luxor' },
    country: 'EG',
    center: { lat: 25.6872, lng: 32.6396 },
    radiusKm: 10,
    landmark: { de: 'Karnak-Tempel', en: 'Karnak Temple' },
    icon: 'pillar',
  },
  {
    id: 'lyon',
    names: { de: 'Lyon', en: 'Lyon' },
    country: 'FR',
    center: { lat: 45.764, lng: 4.8357 },
    radiusKm: 12,
    landmark: { de: 'Basilika Notre-Dame de Fourvière', en: 'Basilica of Notre-Dame de Fourvière' },
    icon: 'church',
  },
  {
    id: 'macau',
    names: { de: 'Macau', en: 'Macau' },
    country: 'MO',
    center: { lat: 22.1987, lng: 113.5439 },
    radiusKm: 8,
    landmark: { de: 'Ruine von São Paulo', en: 'Ruins of St. Paul’s' },
    icon: 'church',
  },
  {
    id: 'madrid',
    names: { de: 'Madrid', en: 'Madrid' },
    country: 'ES',
    center: { lat: 40.4168, lng: -3.7038 },
    radiusKm: 15,
    landmark: { de: 'Königspalast', en: 'Royal Palace' },
    icon: 'castle',
  },
  {
    id: 'marrakesh',
    names: { de: 'Marrakesch', en: 'Marrakesh' },
    country: 'MA',
    center: { lat: 31.6258, lng: -7.9891 },
    radiusKm: 12,
    landmark: { de: 'Koutoubia-Moschee', en: 'Koutoubia Mosque' },
    icon: 'mosque',
  },
  {
    id: 'marseille',
    names: { de: 'Marseille', en: 'Marseille' },
    country: 'FR',
    center: { lat: 43.2965, lng: 5.3698 },
    radiusKm: 15,
    landmark: { de: 'Notre-Dame de la Garde', en: 'Notre-Dame de la Garde' },
    icon: 'church',
  },
  {
    id: 'melbourne',
    names: { de: 'Melbourne', en: 'Melbourne' },
    country: 'AU',
    center: { lat: -37.8136, lng: 144.9631 },
    radiusKm: 25,
    landmark: { de: 'Flinders Street Station', en: 'Flinders Street Station' },
    icon: 'train',
  },
  {
    id: 'mexico-city',
    names: { de: 'Mexiko-Stadt', en: 'Mexico City' },
    country: 'MX',
    center: { lat: 19.4326, lng: -99.1332 },
    radiusKm: 25,
    landmark: { de: 'Kathedrale am Zócalo', en: 'Metropolitan Cathedral' },
    icon: 'church',
  },
  {
    id: 'miami',
    names: { de: 'Miami', en: 'Miami' },
    country: 'US',
    center: { lat: 25.7617, lng: -80.1918 },
    radiusKm: 20,
    landmark: { de: 'South Beach', en: 'South Beach' },
    icon: 'beach',
  },
  {
    id: 'milan',
    names: { de: 'Mailand', en: 'Milan' },
    country: 'IT',
    center: { lat: 45.4642, lng: 9.19 },
    radiusKm: 12,
    landmark: { de: 'Mailänder Dom', en: 'Milan Cathedral' },
    icon: 'church',
  },
  {
    id: 'montreal',
    names: { de: 'Montreal', en: 'Montreal' },
    country: 'CA',
    center: { lat: 45.5017, lng: -73.5673 },
    radiusKm: 15,
    landmark: { de: 'Basilika Notre-Dame', en: 'Notre-Dame Basilica' },
    icon: 'church',
  },
  {
    id: 'moscow',
    names: { de: 'Moskau', en: 'Moscow' },
    country: 'RU',
    center: { lat: 55.7539, lng: 37.6208 },
    radiusKm: 25,
    landmark: { de: 'Basilius-Kathedrale', en: 'Saint Basil’s Cathedral' },
    icon: 'church',
  },
  {
    id: 'mumbai',
    names: { de: 'Mumbai', en: 'Mumbai' },
    country: 'IN',
    center: { lat: 18.9388, lng: 72.8354 },
    radiusKm: 25,
    landmark: { de: 'Gateway of India', en: 'Gateway of India' },
    icon: 'pillar',
  },
  {
    id: 'munich',
    names: { de: 'München', en: 'Munich' },
    country: 'DE',
    center: { lat: 48.1374, lng: 11.5755 },
    radiusKm: 15,
    landmark: { de: 'Hofbräuhaus', en: 'Hofbräuhaus' },
    icon: 'beer',
  },
  {
    id: 'naples',
    names: { de: 'Neapel', en: 'Naples' },
    country: 'IT',
    center: { lat: 40.8518, lng: 14.2681 },
    radiusKm: 12,
    landmark: { de: 'Vesuv', en: 'Mount Vesuvius' },
    icon: 'pizza',
  },
  {
    id: 'new-delhi',
    names: { de: 'Neu-Delhi', en: 'New Delhi' },
    country: 'IN',
    center: { lat: 28.6139, lng: 77.209 },
    radiusKm: 25,
    landmark: { de: 'Rotes Fort', en: 'Red Fort' },
    icon: 'castle',
  },
  {
    id: 'new-orleans',
    names: { de: 'New Orleans', en: 'New Orleans' },
    country: 'US',
    center: { lat: 29.9584, lng: -90.0644 },
    radiusKm: 12,
    landmark: { de: 'French Quarter', en: 'French Quarter' },
    icon: 'music',
  },
  {
    id: 'new-york',
    names: { de: 'New York', en: 'New York' },
    country: 'US',
    center: { lat: 40.7128, lng: -74.006 },
    radiusKm: 25,
    landmark: { de: 'Empire State Building', en: 'Empire State Building' },
    icon: 'office-building',
  },
  {
    id: 'nice',
    names: { de: 'Nizza', en: 'Nice' },
    country: 'FR',
    center: { lat: 43.7102, lng: 7.262 },
    radiusKm: 10,
    landmark: { de: 'Promenade des Anglais', en: 'Promenade des Anglais' },
    icon: 'beach',
  },
  {
    id: 'nuremberg',
    names: { de: 'Nürnberg', en: 'Nuremberg' },
    country: 'DE',
    center: { lat: 49.4521, lng: 11.0767 },
    radiusKm: 10,
    landmark: { de: 'Kaiserburg', en: 'Imperial Castle' },
    icon: 'castle',
  },
  {
    id: 'osaka',
    names: { de: 'Ōsaka', en: 'Osaka' },
    country: 'JP',
    center: { lat: 34.6937, lng: 135.5023 },
    radiusKm: 20,
    landmark: { de: 'Burg Ōsaka', en: 'Osaka Castle' },
    icon: 'castle',
  },
  {
    id: 'oslo',
    names: { de: 'Oslo', en: 'Oslo' },
    country: 'NO',
    center: { lat: 59.9139, lng: 10.7522 },
    radiusKm: 12,
    landmark: { de: 'Opernhaus Oslo', en: 'Oslo Opera House' },
    icon: 'theater',
  },
  {
    id: 'palma',
    names: { de: 'Palma', en: 'Palma' },
    country: 'ES',
    center: { lat: 39.5696, lng: 2.6502 },
    radiusKm: 10,
    landmark: { de: 'Kathedrale La Seu', en: 'Palma Cathedral' },
    icon: 'church',
  },
  {
    id: 'paris',
    names: { de: 'Paris', en: 'Paris' },
    country: 'FR',
    center: { lat: 48.8566, lng: 2.3522 },
    radiusKm: 20,
    landmark: { de: 'Louvre', en: 'Louvre' },
    icon: 'palette',
  },
  {
    id: 'phuket',
    names: { de: 'Phuket', en: 'Phuket' },
    country: 'TH',
    center: { lat: 7.8804, lng: 98.3923 },
    radiusKm: 20,
    landmark: { de: 'Patong Beach', en: 'Patong Beach' },
    icon: 'beach',
  },
  {
    id: 'porto',
    names: { de: 'Porto', en: 'Porto' },
    country: 'PT',
    center: { lat: 41.1579, lng: -8.6291 },
    radiusKm: 10,
    landmark: { de: 'Ponte Dom Luís I', en: 'Dom Luís I Bridge' },
    icon: 'bridge',
  },
  {
    id: 'prague',
    names: { de: 'Prag', en: 'Prague' },
    country: 'CZ',
    center: { lat: 50.0875, lng: 14.4213 },
    radiusKm: 12,
    landmark: { de: 'Karlsbrücke', en: 'Charles Bridge' },
    icon: 'bridge',
  },
  {
    id: 'quebec-city',
    names: { de: 'Québec', en: 'Quebec City' },
    country: 'CA',
    center: { lat: 46.8139, lng: -71.208 },
    radiusKm: 10,
    landmark: { de: 'Château Frontenac', en: 'Château Frontenac' },
    icon: 'castle',
  },
  {
    id: 'queenstown',
    names: { de: 'Queenstown', en: 'Queenstown' },
    country: 'NZ',
    center: { lat: -45.0312, lng: 168.6626 },
    radiusKm: 15,
    landmark: { de: 'Lake Wakatipu', en: 'Lake Wakatipu' },
    icon: 'waves',
  },
  {
    id: 'reykjavik',
    names: { de: 'Reykjavík', en: 'Reykjavík' },
    country: 'IS',
    center: { lat: 64.1466, lng: -21.9426 },
    radiusKm: 10,
    landmark: { de: 'Hallgrímskirkja', en: 'Hallgrímskirkja' },
    icon: 'church',
  },
  {
    id: 'riga',
    names: { de: 'Riga', en: 'Riga' },
    country: 'LV',
    center: { lat: 56.9496, lng: 24.1052 },
    radiusKm: 10,
    landmark: { de: 'Schwarzhäupterhaus', en: 'House of the Blackheads' },
    icon: 'home-city',
  },
  {
    id: 'rio-de-janeiro',
    names: { de: 'Rio de Janeiro', en: 'Rio de Janeiro' },
    country: 'BR',
    center: { lat: -22.9068, lng: -43.1729 },
    radiusKm: 25,
    landmark: { de: 'Cristo Redentor', en: 'Christ the Redeemer' },
    icon: 'church',
  },
  {
    id: 'rome',
    names: { de: 'Rom', en: 'Rome' },
    country: 'IT',
    center: { lat: 41.8967, lng: 12.4822 },
    radiusKm: 15,
    landmark: { de: 'Kolosseum', en: 'Colosseum' },
    icon: 'stadium',
  },
  {
    id: 'rothenburg-ob-der-tauber',
    names: { de: 'Rothenburg ob der Tauber', en: 'Rothenburg ob der Tauber' },
    country: 'DE',
    center: { lat: 49.3772, lng: 10.1789 },
    radiusKm: 4,
    landmark: { de: 'Plönlein', en: 'Plönlein' },
    icon: 'home-city',
  },
  {
    id: 'saint-petersburg',
    names: { de: 'Sankt Petersburg', en: 'Saint Petersburg' },
    country: 'RU',
    center: { lat: 59.9343, lng: 30.3351 },
    radiusKm: 20,
    landmark: { de: 'Eremitage', en: 'Hermitage Museum' },
    icon: 'palette',
  },
  {
    id: 'salzburg',
    names: { de: 'Salzburg', en: 'Salzburg' },
    country: 'AT',
    center: { lat: 47.8095, lng: 13.055 },
    radiusKm: 8,
    landmark: { de: 'Festung Hohensalzburg', en: 'Hohensalzburg Fortress' },
    icon: 'castle',
  },
  {
    id: 'san-francisco',
    names: { de: 'San Francisco', en: 'San Francisco' },
    country: 'US',
    center: { lat: 37.7749, lng: -122.4194 },
    radiusKm: 15,
    landmark: { de: 'Golden Gate Bridge', en: 'Golden Gate Bridge' },
    icon: 'bridge',
  },
  {
    id: 'santorini',
    names: { de: 'Santorini', en: 'Santorini' },
    country: 'GR',
    center: { lat: 36.4167, lng: 25.4317 },
    radiusKm: 15,
    landmark: { de: 'Blaue Kuppeln von Oia', en: 'Blue domes of Oia' },
    icon: 'island',
  },
  {
    id: 'sao-paulo',
    names: { de: 'São Paulo', en: 'São Paulo' },
    country: 'BR',
    center: { lat: -23.5505, lng: -46.6333 },
    radiusKm: 30,
    landmark: { de: 'Avenida Paulista', en: 'Avenida Paulista' },
    icon: 'office-building',
  },
  {
    id: 'seoul',
    names: { de: 'Seoul', en: 'Seoul' },
    country: 'KR',
    center: { lat: 37.5665, lng: 126.978 },
    radiusKm: 25,
    landmark: { de: 'Gyeongbokgung-Palast', en: 'Gyeongbokgung Palace' },
    icon: 'castle',
  },
  {
    id: 'seville',
    names: { de: 'Sevilla', en: 'Seville' },
    country: 'ES',
    center: { lat: 37.3891, lng: -5.9845 },
    radiusKm: 10,
    landmark: { de: 'Kathedrale mit Giralda', en: 'Seville Cathedral and Giralda' },
    icon: 'church',
  },
  {
    id: 'shanghai',
    names: { de: 'Shanghai', en: 'Shanghai' },
    country: 'CN',
    center: { lat: 31.2304, lng: 121.4737 },
    radiusKm: 30,
    landmark: { de: 'The Bund', en: 'The Bund' },
    icon: 'office-building',
  },
  {
    id: 'siem-reap',
    names: { de: 'Siem Reap', en: 'Siem Reap' },
    country: 'KH',
    center: { lat: 13.3671, lng: 103.8448 },
    radiusKm: 15,
    landmark: { de: 'Angkor Wat', en: 'Angkor Wat' },
    icon: 'temple-hindu',
  },
  {
    id: 'singapore',
    names: { de: 'Singapur', en: 'Singapore' },
    country: 'SG',
    center: { lat: 1.2903, lng: 103.8519 },
    radiusKm: 20,
    landmark: { de: 'Marina Bay Sands', en: 'Marina Bay Sands' },
    icon: 'office-building',
  },
  {
    id: 'stockholm',
    names: { de: 'Stockholm', en: 'Stockholm' },
    country: 'SE',
    center: { lat: 59.3293, lng: 18.0686 },
    radiusKm: 15,
    landmark: { de: 'Vasa-Museum', en: 'Vasa Museum' },
    icon: 'ship-wheel',
  },
  {
    id: 'stuttgart',
    names: { de: 'Stuttgart', en: 'Stuttgart' },
    country: 'DE',
    center: { lat: 48.7758, lng: 9.1829 },
    radiusKm: 12,
    landmark: { de: 'Neues Schloss', en: 'New Palace' },
    icon: 'castle',
  },
  {
    id: 'sydney',
    names: { de: 'Sydney', en: 'Sydney' },
    country: 'AU',
    center: { lat: -33.8688, lng: 151.2093 },
    radiusKm: 25,
    landmark: { de: 'Opernhaus Sydney', en: 'Sydney Opera House' },
    icon: 'theater',
  },
  {
    id: 'taipei',
    names: { de: 'Taipeh', en: 'Taipei' },
    country: 'TW',
    center: { lat: 25.033, lng: 121.5654 },
    radiusKm: 20,
    landmark: { de: 'Taipei 101', en: 'Taipei 101' },
    icon: 'office-building',
  },
  {
    id: 'tallinn',
    names: { de: 'Tallinn', en: 'Tallinn' },
    country: 'EE',
    center: { lat: 59.437, lng: 24.7536 },
    radiusKm: 8,
    landmark: { de: 'Altstadt', en: 'Old Town' },
    icon: 'castle',
  },
  {
    id: 'tokyo',
    names: { de: 'Tokio', en: 'Tokyo' },
    country: 'JP',
    center: { lat: 35.6812, lng: 139.7671 },
    radiusKm: 30,
    landmark: { de: 'Shibuya-Kreuzung', en: 'Shibuya Crossing' },
    icon: 'city-variant',
  },
  {
    id: 'toronto',
    names: { de: 'Toronto', en: 'Toronto' },
    country: 'CA',
    center: { lat: 43.6532, lng: -79.3832 },
    radiusKm: 20,
    landmark: { de: 'CN Tower', en: 'CN Tower' },
    icon: 'city-variant',
  },
  {
    id: 'ubud',
    names: { de: 'Ubud (Bali)', en: 'Ubud (Bali)' },
    country: 'ID',
    center: { lat: -8.5069, lng: 115.2625 },
    radiusKm: 10,
    landmark: { de: 'Reisterrassen von Tegallalang', en: 'Tegallalang Rice Terraces' },
    icon: 'palm-tree',
  },
  {
    id: 'valencia',
    names: { de: 'Valencia', en: 'Valencia' },
    country: 'ES',
    center: { lat: 39.4699, lng: -0.3763 },
    radiusKm: 12,
    landmark: { de: 'Stadt der Künste und der Wissenschaften', en: 'City of Arts and Sciences' },
    icon: 'theater',
  },
  {
    id: 'valletta',
    names: { de: 'Valletta', en: 'Valletta' },
    country: 'MT',
    center: { lat: 35.8989, lng: 14.5146 },
    radiusKm: 6,
    landmark: { de: 'Grand Harbour', en: 'Grand Harbour' },
    icon: 'ship-wheel',
  },
  {
    id: 'vancouver',
    names: { de: 'Vancouver', en: 'Vancouver' },
    country: 'CA',
    center: { lat: 49.2827, lng: -123.1207 },
    radiusKm: 15,
    landmark: { de: 'Stanley Park', en: 'Stanley Park' },
    icon: 'tree',
  },
  {
    id: 'varanasi',
    names: { de: 'Varanasi', en: 'Varanasi' },
    country: 'IN',
    center: { lat: 25.3176, lng: 82.9739 },
    radiusKm: 10,
    landmark: { de: 'Ghats am Ganges', en: 'Ghats of the Ganges' },
    icon: 'temple-hindu',
  },
  {
    id: 'venice',
    names: { de: 'Venedig', en: 'Venice' },
    country: 'IT',
    center: { lat: 45.438, lng: 12.3358 },
    radiusKm: 6,
    landmark: { de: 'Canal Grande', en: 'Grand Canal' },
    icon: 'gondola',
  },
  {
    id: 'verona',
    names: { de: 'Verona', en: 'Verona' },
    country: 'IT',
    center: { lat: 45.4384, lng: 10.9916 },
    radiusKm: 8,
    landmark: { de: 'Arena di Verona', en: 'Verona Arena' },
    icon: 'theater',
  },
  {
    id: 'vienna',
    names: { de: 'Wien', en: 'Vienna' },
    country: 'AT',
    center: { lat: 48.2082, lng: 16.3738 },
    radiusKm: 15,
    landmark: { de: 'Riesenrad im Prater', en: 'Prater Giant Ferris Wheel' },
    icon: 'ferris-wheel',
  },
  {
    id: 'warsaw',
    names: { de: 'Warschau', en: 'Warsaw' },
    country: 'PL',
    center: { lat: 52.2297, lng: 21.0122 },
    radiusKm: 15,
    landmark: { de: 'Kulturpalast', en: 'Palace of Culture and Science' },
    icon: 'office-building',
  },
  {
    id: 'washington',
    names: { de: 'Washington, D.C.', en: 'Washington, D.C.' },
    country: 'US',
    center: { lat: 38.8895, lng: -77.0353 },
    radiusKm: 15,
    landmark: { de: 'Kapitol', en: 'United States Capitol' },
    icon: 'bank',
  },
  {
    id: 'xian',
    names: { de: 'Xi’an', en: 'Xi’an' },
    country: 'CN',
    center: { lat: 34.3416, lng: 108.9398 },
    radiusKm: 20,
    landmark: { de: 'Stadtmauer', en: 'City Wall' },
    icon: 'castle',
  },
  {
    id: 'zanzibar',
    names: { de: 'Sansibar', en: 'Zanzibar' },
    country: 'TZ',
    center: { lat: -6.163, lng: 39.188 },
    radiusKm: 8,
    landmark: { de: 'Stone Town', en: 'Stone Town' },
    icon: 'island',
  },
  {
    id: 'zurich',
    names: { de: 'Zürich', en: 'Zurich' },
    country: 'CH',
    center: { lat: 47.3769, lng: 8.5417 },
    radiusKm: 10,
    landmark: { de: 'Grossmünster', en: 'Grossmünster' },
    icon: 'church',
  },
];
