/** Icon glyphs (MaterialCommunityIcons names) a city badge may use. */
export const CITY_BADGE_ICONS = [
  'bridge',
  'church',
  'mosque',
  'temple-buddhist',
  'temple-hindu',
  'pillar',
  'city-variant',
  'ferris-wheel',
  'island',
  'beach',
  'palm-tree',
  'office-building',
  'castle',
  'bank',
  'ship-wheel',
  'sail-boat',
  'synagogue',
  'stadium',
  'theater',
  'palette',
  'glass-wine',
  'beer',
  'coffee',
  'pizza',
  'food-croissant',
  'tree',
  'flower',
  'waves',
  'snowflake',
  'camera',
  'music',
  'home-city',
  'lighthouse',
  'gondola',
  'train',
  'tram',
] as const;

export type CityBadgeIcon = (typeof CITY_BADGE_ICONS)[number];
