import { useEffect, useRef, useState } from 'react';
import {
  AccessibilityInfo,
  Animated,
  Easing,
  type ColorValue,
  View,
  type ImageSourcePropType,
  type StyleProp,
  type ViewStyle,
} from 'react-native';
import { radii, spacing, sys } from '../theme';
import { Text } from './Text';
import idlePng from '../../assets/mascot/tuu_01_idle_front.png';
import walkPng from '../../assets/mascot/tuu_02_walk_forward.png';
import wavePng from '../../assets/mascot/tuu_03_wave_hello.png';
import pointPng from '../../assets/mascot/tuu_04_pointing_direction.png';
import listenPng from '../../assets/mascot/tuu_05_listening.png';
import thinkPng from '../../assets/mascot/tuu_06_thinking.png';
import mapPng from '../../assets/mascot/tuu_07_map_planning.png';
import presentPng from '../../assets/mascot/tuu_08_presenting.png';
import celebratePng from '../../assets/mascot/tuu_09_excited_jump.png';
import relaxPng from '../../assets/mascot/tuu_10_sit_relaxed.png';

/**
 * Tuu, the guide character (D46). Poses are app-ready copies generated by `pnpm mascot`
 * from the owner's originals in `assets/mascot`.
 */
const POSES = {
  idle: idlePng,
  walk: walkPng,
  wave: wavePng,
  point: pointPng,
  listen: listenPng,
  think: thinkPng,
  map: mapPng,
  present: presentPng,
  celebrate: celebratePng,
  relax: relaxPng,
} satisfies Record<string, ImageSourcePropType>;

export type MascotPose = keyof typeof POSES;

function useReduceMotion() {
  const [reduceMotion, setReduceMotion] = useState(false);
  useEffect(() => {
    void AccessibilityInfo.isReduceMotionEnabled().then(setReduceMotion);
    const sub = AccessibilityInfo.addEventListener('reduceMotionChanged', setReduceMotion);
    return () => sub.remove();
  }, []);
  return reduceMotion;
}

interface Props {
  pose: MascotPose;
  /** Edge length in points (the artwork is square). */
  size?: number;
  /** Screen-reader label; without it Tuu is decorative and hidden from assistive tech. */
  label?: string;
  /** Gentle breathing bob while visible (default on); the celebrate pose hops instead. */
  idle?: boolean;
  /** Pop-in entrance on mount (default on). */
  entrance?: boolean;
  style?: StyleProp<ViewStyle>;
}

/**
 * Tuu with a pop-in entrance and a subtle idle motion (native driver only). Both are skipped under
 * "reduce motion". Never a loading indicator by itself: loaders stay the SpinningMark.
 */
export function Mascot({ pose, size = 96, label, idle = true, entrance = true, style }: Props) {
  const reduceMotion = useReduceMotion();
  const enter = useRef(new Animated.Value(entrance ? 0 : 1)).current;
  const loop = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    if (!entrance) return;
    if (reduceMotion) {
      enter.setValue(1);
      return;
    }
    const anim = Animated.spring(enter, {
      toValue: 1,
      friction: 6,
      tension: 80,
      useNativeDriver: true,
    });
    anim.start();
    return () => anim.stop();
  }, [entrance, reduceMotion, enter]);

  useEffect(() => {
    if (!idle || reduceMotion) return;
    const half = pose === 'celebrate' ? 420 : 1600;
    const anim = Animated.loop(
      Animated.sequence([
        Animated.timing(loop, {
          toValue: 1,
          duration: half,
          easing: Easing.inOut(Easing.sin),
          useNativeDriver: true,
        }),
        Animated.timing(loop, {
          toValue: 0,
          duration: half,
          easing: Easing.inOut(Easing.sin),
          useNativeDriver: true,
        }),
      ]),
    );
    anim.start();
    return () => {
      anim.stop();
      loop.setValue(0);
    };
  }, [idle, reduceMotion, pose, loop]);

  const lift = pose === 'celebrate' ? size * 0.06 : size * 0.025;
  const translateY = loop.interpolate({ inputRange: [0, 1], outputRange: [0, -lift] });
  const breathe = loop.interpolate({ inputRange: [0, 1], outputRange: [1, 1.015] });
  const scale = enter.interpolate({ inputRange: [0, 1], outputRange: [0.6, 1] });

  return (
    <View
      style={[{ width: size, height: size }, style]}
      accessible={!!label}
      accessibilityRole={label ? 'image' : undefined}
      accessibilityLabel={label}
      accessibilityElementsHidden={!label}
      importantForAccessibility={label ? 'yes' : 'no-hide-descendants'}
      pointerEvents="none"
    >
      <Animated.View style={{ opacity: enter, transform: [{ scale }] }}>
        <Animated.Image
          source={POSES[pose]}
          resizeMode="contain"
          style={{
            width: size,
            height: size,
            transform: [{ translateY }, { scaleY: breathe }],
          }}
        />
      </Animated.View>
    </View>
  );
}

interface TipProps {
  pose: MascotPose;
  text: string;
  size?: number;
  /** Bubble fill; use `sys.elevated` on grouped (grey) screens. */
  bubble?: ColorValue;
  style?: StyleProp<ViewStyle>;
}

/** Tuu next to a short one-line hint in a speech bubble. The text is read; Tuu stays decorative. */
export function MascotTip({ pose, text, size = 56, bubble = sys.fill, style }: TipProps) {
  return (
    <View style={[{ flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, style]}>
      <Mascot pose={pose} size={size} />
      <View style={{ flex: 1, flexDirection: 'row', alignItems: 'center' }}>
        <View
          style={{
            width: 0,
            height: 0,
            borderTopWidth: 7,
            borderBottomWidth: 7,
            borderRightWidth: 8,
            borderTopColor: 'transparent',
            borderBottomColor: 'transparent',
            borderRightColor: bubble,
          }}
        />
        <View
          style={{
            flex: 1,
            backgroundColor: bubble,
            borderRadius: radii.md,
            paddingHorizontal: 12,
            paddingVertical: 10,
          }}
        >
          <Text variant="subheadline" color={sys.label}>
            {text}
          </Text>
        </View>
      </View>
    </View>
  );
}
