/** Primary source languages by ISO 3166-1 alpha-2 country; used to prefer the richest Wikipedia editions. */
const COUNTRY_LANGS: Record<string, string[]> = {
  DE: ['de'],
  AT: ['de'],
  CH: ['de', 'fr', 'it'],
  LI: ['de'],
  FR: ['fr'],
  IT: ['it'],
  ES: ['es'],
  PT: ['pt'],
  NL: ['nl'],
  BE: ['nl', 'fr'],
  LU: ['fr', 'de'],
  DK: ['da'],
  SE: ['sv'],
  NO: ['no'],
  FI: ['fi'],
  IS: ['is'],
  PL: ['pl'],
  CZ: ['cs'],
  SK: ['sk'],
  HU: ['hu'],
  RO: ['ro'],
  BG: ['bg'],
  GR: ['el'],
  HR: ['hr'],
  SI: ['sl'],
  RS: ['sr'],
  TR: ['tr'],
  RU: ['ru'],
  UA: ['uk'],
  JP: ['ja'],
  CN: ['zh'],
  TW: ['zh'],
  KR: ['ko'],
  TH: ['th'],
  VN: ['vi'],
  ID: ['id'],
  IN: ['hi'],
  IL: ['he'],
  EG: ['ar'],
  MA: ['ar', 'fr'],
  MX: ['es'],
  AR: ['es'],
  CL: ['es'],
  CO: ['es'],
  PE: ['es'],
  BR: ['pt'],
  US: ['en'],
  GB: ['en'],
  IE: ['en'],
  CA: ['en', 'fr'],
  AU: ['en'],
  NZ: ['en'],
  ZA: ['en'],
};

/** Local language(s) first, then German and English (spec 4.1). Deduplicated. */
export function sourceLangsFor(countryCode: string): string[] {
  const local = COUNTRY_LANGS[countryCode.toUpperCase()] ?? [];
  return [...new Set([...local, 'de', 'en'])];
}
