import {
  PoiSchema,
  NarrationLangSchema,
  budgetDecision,
  factSheetPrompt,
  fallbackFactSheet,
  normalizeFactSheet,
  sourceLangsFor,
  sourceText,
  verifyFactSheet,
  type FactSheet,
  type FactSheetSourceInput,
  type SourceBundle,
} from '@tuur/shared';
import { z } from 'zod';
import { budgetedLlm } from '../providers/budgeted';
import { loadAiConfig } from '../util/aiConfig';
import { consumeRateLimit, RateLimitError } from '../util/rateLimit';
import { spentToday } from '../util/usage';
import { NarrationError } from '../narration/service';
import type { TeaserDeps } from '../narration/teaser';

/** A deterministic (non-AI) sheet is re-tried after this long, e.g. once the budget or provider recovers. */
export const FALLBACK_SHEET_TTL_MS = 60 * 60_000;

export const GetFactSheetRequestSchema = z.object({
  poiId: z.string().min(1).max(120),
  lang: NarrationLangSchema,
  access: z
    .object({
      tourId: z.string().max(200).optional(),
      groupId: z
        .string()
        .regex(/^[A-Za-z0-9]{10,40}$/)
        .optional(),
      mode: z.enum(['tour', 'planned', 'fork', 'roam']).optional(),
      sessionId: z.string().max(200).optional(),
    })
    .optional(),
});

export interface FactSheetResult {
  sheet: FactSheet;
  origin: 'ai' | 'fallback';
  cached: boolean;
}

/** Best readable source text for the deterministic path: Wikipedia in the reader's language, admin facts, OSM. */
export function bundleToSheetInput(
  bundle: SourceBundle,
  lang: string,
): FactSheetSourceInput & { name: string } {
  const wiki = bundle.wikipedia.find((w) => w.lang === lang) ?? bundle.wikipedia[0];
  const text =
    wiki?.extract ??
    (bundle.adminFacts.join(' ') ||
      bundle.osmTags[`description:${lang}`] ||
      bundle.osmTags['description'] ||
      '');
  return { name: bundle.poiName, text, osmTags: bundle.osmTags, wikidata: bundle.facts, lang };
}

/**
 * Structured fact sheet for the place card. Generated by the lite model from the place's sources only (prompt and
 * JSON shape in `@tuur/shared`), numbers verified against the sources, cached per place/language/prompt version.
 * When the model is paused, over budget, fails or is unverifiable, the deterministic sheet built from the same
 * sources is returned instead (cached for a short time only).
 */
export async function getFactSheet(deps: TeaserDeps, uid: string, raw: unknown): Promise<FactSheetResult> {
  const parsed = GetFactSheetRequestSchema.safeParse(raw);
  if (!parsed.success) throw new NarrationError('invalid-argument', 'Invalid request');
  const { poiId, lang, access } = parsed.data;
  const cfg = await (deps.config ?? (() => loadAiConfig(deps.db, deps.now())))();
  const snap = await deps.db.collection('pois').doc(poiId).get();
  if (!snap.exists || snap.get('hidden')) throw new NarrationError('not-found', 'POI not found');
  const poi = PoiSchema.parse(snap.data());
  await deps.authorize?.(uid, poi, access);
  const ref = deps.db
    .collection('factSheets')
    .doc(`${poiId}__${lang}__${cfg.promptVersion}`.replace(/[^A-Za-z0-9_-]/g, '_'));
  const hit = await ref.get();
  if (hit.exists) {
    const cached = FactSheetCacheSchema.safeParse(hit.data());
    if (
      cached.success &&
      cached.data.poiUpdatedAt === poi.updatedAt &&
      (cached.data.origin === 'ai' || cached.data.createdAt + FALLBACK_SHEET_TTL_MS > deps.now())
    )
      return { sheet: cached.data.sheet, origin: cached.data.origin, cached: true };
  }

  try {
    await consumeRateLimit(deps.db, `factsheet_user_${uid}`, 120, 3600_000, deps.now());
  } catch (e) {
    if (e instanceof RateLimitError)
      throw new NarrationError('resource-exhausted', 'Too many requests', { retryAfterMs: e.retryAfterMs });
    throw e;
  }
  const bundle = await deps.sources.gather(poi, [lang, ...sourceLangsFor('XX')]);
  const input = bundleToSheetInput(bundle, lang);
  const sources = sourceText(bundle);

  let result: { sheet: FactSheet; origin: 'ai' | 'fallback' } | undefined;
  const budget = budgetDecision(cfg, await spentToday(deps.db, poi.tile, deps.now()));
  if (budget.allowed && sources.trim().length > poi.name.length) {
    try {
      const { system, user } = factSheetPrompt({ name: poi.name, lang, sources });
      const out = await budgetedLlm(deps.llm, deps.db, cfg, deps.now, { tile: poi.tile }).factSheet({
        model: cfg.models.lite,
        system,
        user,
        fallback: input,
      });
      const normalized = normalizeFactSheet(out.output);
      const sheet = normalized ? verifyFactSheet(normalized, sources) : undefined;
      if (sheet) result = { sheet, origin: 'ai' };
    } catch {
      // Budget, provider or schema failure: use the deterministic sheet below.
    }
  }
  result ??= (() => {
    const sheet = fallbackFactSheet(input);
    return sheet ? { sheet, origin: 'fallback' as const } : undefined;
  })();
  if (!result) throw new NarrationError('not-found', 'No place information', { reason: 'no_sources' });
  await ref.set({
    ...result,
    poiId,
    lang,
    promptVersion: cfg.promptVersion,
    poiUpdatedAt: poi.updatedAt,
    createdAt: deps.now(),
  });
  return { ...result, cached: false };
}

const FactSheetCacheSchema = z.object({
  sheet: z.custom<FactSheet>((v) => normalizeFactSheet(v) !== undefined),
  origin: z.enum(['ai', 'fallback']),
  poiUpdatedAt: z.number(),
  createdAt: z.number(),
});
